name: music_player
description: A modern, asset-less music player built with Flutter, focusing on audio health and a stunning UI/UX.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio Playback
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11 # Ekolayzer ve arkaplan için eklendi
  audio_session: ^0.1.18

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local Audio Query
  on_audio_query: ^2.9.0
  permission_handler: ^11.0.1

  # UI & Effects
  glassmorphism: ^3.0.0 # Helper for Glassmorphism, but we will build our own for more control.
  palette_generator: ^0.3.3+3 # To extract colors from album art
  shared_preferences: ^2.2.2 # For storing favorites
  sensors_plus: ^4.0.2 # For shake detection
  fl_chart: ^0.68.0 # For charts in health dashboard
  
  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true